spring:
  config:
    activate:
      on-profile:
      - prod

server:
  port: 6060


---
spring:
  config:
    activate:
      on-profile:
      - dev
      - sit
      - uat

server:
  port: 6060
